### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by Kubrick** [vivescere/puck#1]
I wanted to try out your script but when I launch it it returns:
`Traceback (most recent call last):
  File "puck.py", line 8, in <module>
    import urllib.request
ImportError: No module named request`

As I am not used to python it probably is a mistake on my side but I can't put my finger on it...

**Comment by Kubrick** [comment]
If I run the script with python3, I don't have this error but this one
`Traceback (most recent call last):
  File "puck.py", line 11, in <module>
    from colorthief import ColorThief
ImportError: No module named 'colorthief'
`

Except I'm pretty sure I've installed it…

**Comment by vivescere** [comment]
Sorry for the delay! You've probably installed pip for python2, not python3. If you tell me your distro, I could tell you the exact package.

**Comment by Kubrick** [comment]
Thanks, I'm using ubuntu 16.04.

**Comment by vivescere** [comment]
Install the `python3-pip` package, and then run `pip3 install colorthief`.
